add the possibility for hidden password input
adfinis-sygroup/pyark pull request #16
Opened 2019-10-17 12:58 UTC by dondeli

Hi
Sometime, hidden password entry can be useful. The code should be reverse compatible.

Regards
Michel

2019-11-01 11:44 UTC, karras requested changes

2019-11-01 11:44 UTC, karras commented on pyark/__init__.py
> +
Please remove the whitespaces on line 465 and make flake8 / Travis green again. :)

2019-11-05 09:00 UTC, karras approved these changes
LGTM

2019-11-05 09:01 UTC, merged

2019-11-05 09:01 UTC, karras commented
Thanks!

2019-11-05 10:03 UTC, karras commented
@dondeli I've published the new version to PyPi (https://pypi.org/project/pyark/). Have fun!

2019-11-05 10:07 UTC, dondeli commented
@karras THX a lot!